name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

env:
  configuration: Release
  productNamespacePrefix: "XamlNameReferenceGenerator"

jobs:
  build:
    runs-on: windows-latest
    outputs:
      nbgv: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15

    - name: NBGV
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: NuGet Restore
      run: dotnet restore
      working-directory: src
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild /t:build,pack /maxcpucount /p:NoPackageAnalysis=true /verbosity:minimal /p:Configuration=${{ env.configuration }}
      working-directory: src

    - name: Run Unit Tests and Generate Coverage
      uses: glennawatson/coverlet-msbuild@v1
      with:
        project-files: 'src/**/*.Tests.csproj'
        no-build: true
        exclude-filter: '[${{env.productNamespacePrefix}}.*.Tests.*]*'
        include-filter: '[${{env.productNamespacePrefix}}*]*'
        output-format: cobertura
        output: '../../artifacts/'
        configuration: ${{ env.configuration }}
        working-directory: src

    - name: Create NuGet Artifacts
      uses: actions/upload-artifact@master
      with:
        name: nuget
        path: '**/*.nupkg'
